language: java
jdk:
- openjdk11

env:
  global:
  - secure: "K0jeyhLuaCRXQKaBloZ2G3uaXaaE5ARiZh7ltzsw9GSZH33vdSObYnKSnHA4pnEwoP0KRCxoJ3issPRgw2dMJdqvke4p5rSJeK+3C/3Rw0iJfTMFeSogS8epHxHMKwoXq0X/nOsi8dGiDFGj+tzhVqJarKlKiDsbcaz/pfEraQWzzPPFAgc2Cj907L38drhfev6VGu1LzhSfgA2YcLihNy0Br5Q9iqa2X898dRKTseAJ5PBtdB0CfvKzF/Q+V7IwBCwPcS0yC6y5+4xnr/r4qlE5VBJ4II7RXePBLAwNyBxUQhlJkQyNOmgSdNqSVXY6Wa00/q/wF7Z5HkWgLefoy2cd3GARGkoQxge3EQrdRdYYGm6FVeZ/+/cA9VqMa8lrhHYnspj+IgL3ssHvuHJAhLSEry+rgyXsZrdMcY4/ZRxwnq+EdqAGI1oNTzkleoRKQ62G3JTOUm3UxxqrBpSsH0bqzEVbbMxAthrOpn1ypxuioB+kXkJBtkMfEXSQO/I7od6+zY6nst4oolhR1GAcMS7f+H1RYXj322WrlXtAJhrmBb9xT/gsSMppnqepxfuXRT6NRhh55gsSNdFmNW9o8/CopfawsOe0h/3cQOtoQ4NyEQs531vM7+qep6Wqtrrh3iKumAinNh8SwxwSDCbZozARwWoglcC71t1ZRmGzY9k="
  - secure: "kMD3HZ8kEyyVzPqKfwMz6lYtwIlh1Lth9sA63oI4/od06hxKzULoWlQyZ0zXcDKuhFws/AeA/yM44bPba2eH6H0l1kCfngsNhG7ggFy0KxxPmtyqPDeIqFqq6OoUynuAn7o8X5bbqbZP91Wq7TLlWdCcc9N5/5CquafNNVKtp/Lj8GP3naDmD4u/0qYL7C0Pf550tfrlhjXaY/znrwxP7ftXT8/l5RYzC4Tfz2ZV1s8fulfHevQxZlClUSWBl2e43nMos/dl5h23vZq76JCsKZ9U9wH5BeabLrDdflQhBp7vn6VGscjPYBqeK+JuiutBLI+8Ti1lKCnQnQhC+SWOkhIwpLPALfIjLauh1PQCyFM7zkbgqznNcaQEJb9J9WJLHUv3nQLDuqFtNMH81D3YV/zov5NvhXtVk+fkFGJ62cdWC7rlG8J+Xk4WfIgiRgDbvgl8FiUaa/LIuush2z+0ECRy+a9OsERNF2W2T5/OXhoFg7TZSSOylYowu14Veo8hGSEpo4QHpoO2CoSPUdS48bhGgFo7aQmbpCmUqeCY1JNPQe1lK9riciYufESN9u8IsJiHWZaKhOCvAwdiBqvncOcY7bWtVMNgJAPJejUOg4eDIRzq/EL2CAisFYSJprCZFDUdNcqari355XOUQt4+eGDgEM3UIKaQSU0PBofmxCo="
  - secure: "c8HUUTQAhuZ6kdAA26a0+iwki6iA9f0mJeuFtSEkVPQpxID58wrfRXeKiR00TUeCxj88tfeCmW9PzrhekTZ38rdOV1qaT7ASqJaFc7y0JDFS/n0stvpoae/u0f0LTIAs0msKHXMCrrWF0UJkdL/Wgh2UpN0QzHKUMIPe5Fs3yn3rZQVhG5Dmn8QPg6K9outufpANjBvhXZV8R99nnjCRom+E38mNE6N4KgvmE+PufR6GUoAIu0ZYc+GH9FgtvtqzgWb7MIWIAdrs0Qb9ZS4k+GJJ9M/r6WKMa5xdYgKI5oFSYPbjhgaFOKtylqQf2w6JWsbxruCE41kt0xlrgB3/oYQQaLY15L0JQHuTwayXzLPADOpZf1lWkf3s6cRjSEZZEjtwr8oYV1DyxgPytjyD9n6LUBLfjIL9s/y6jB+q9bmcovlmQv1EaWysChdnJtIsGyWAHuiADCu6oyDSaAbRkRzC76SG61q+pYKtTssC57FLmZEO8DpxAbX8AmDZ/AAERffWxY37+kofAeqK8lGqq/ouu6nyPU8OPksiJ+J8YXatgrnLr/1NiCgFaYwCrj8MZkabLYBUSBpbPICle/MAHVcPOJ8uV5LJ9RKvq9pvLu/3zp5Ecs3i7QoqYOWpHfHlOa+BBojFjzLnEZrjHmeUbwQOyp0yqTI8gVGUc9DlUlY="

jobs:
  include:
    # This job is for running testing against feature pull requests to ensure tests are passing. It also serves as a pre req to deploying.
    - stage: test
      name: 'Run testing'
      install: true
      script:
        - mvn test

    # This job is for deploys to maven central using conventional commits. This job should only run against the master branch when it detects a merge. It should also not execute against forked repos.
    - stage: deploy
      name: 'Deploy to Maven Central'
      if: branch = master
      install: true
      before_script:
        - openssl aes-256-cbc -K $encrypted_906cef29eab6_key -iv $encrypted_906cef29eab6_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xf secrets.tar --directory deploy/
      script: bash deploy/deploy.sh
